#!/usr/bin/env python3
# 常量定义模块 - 存储项目中使用的常量

COMMON_TLDS: tuple = (
    "com", "org", "net", "edu", "gov", "mil", "int",
    "info", "biz", "name", "pro", "aero", "coop", "museum",
    "asia", "cat", "jobs", "mobi", "tel", "travel", "xxx",
    "ac", "ad", "ae", "af", "ag", "ai", "al", "am", "an", "ao",
    "aq", "ar", "as", "at", "au", "aw", "ax", "az",
    "ba", "bb", "bd", "be", "bf", "bg", "bh", "bi", "bj", "bm",
    "bn", "bo", "br", "bs", "bt", "bv", "bw", "by", "bz",
    "ca", "cc", "cd", "cf", "cg", "ch", "ci", "ck", "cl", "cm",
    "cn", "co", "cr", "cu", "cv", "cx", "cy", "cz",
    "de", "dj", "dk", "dm", "do", "dz",
    "ec", "ee", "eg", "eh", "er", "es", "et", "eu",
    "fi", "fj", "fk", "fm", "fo", "fr",
    "ga", "gb", "gd", "ge", "gf", "gg", "gh", "gi", "gl", "gm",
    "gn", "gp", "gq", "gr", "gs", "gt", "gu", "gw", "gy",
    "hk", "hm", "hn", "hr", "ht", "hu",
    "id", "ie", "il", "im", "in", "io", "iq", "ir", "is", "it",
    "je", "jm", "jo", "jp",
    "ke", "kg", "kh", "ki", "km", "kn", "kp", "kr", "kw", "ky", "kz",
    "la", "lb", "lc", "li", "lk", "lr", "ls", "lt", "lu", "lv", "ly",
    "ma", "mc", "md", "me", "mg", "mh", "mk", "ml", "mm", "mn", "mo",
    "mp", "mq", "mr", "ms", "mt", "mu", "mv", "mw", "mx", "my", "mz",
    "na", "nc", "ne", "nf", "ng", "ni", "nl", "no", "np", "nr", "nu",
    "nz",
    "om",
    "pa", "pe", "pf", "pg", "ph", "pk", "pl", "pm", "pn", "pr", "ps",
    "pt", "pw", "py",
    "qa",
    "re", "ro", "rs", "ru", "rw",
    "sa", "sb", "sc", "sd", "se", "sg", "sh", "si", "sj", "sk", "sl",
    "sm", "sn", "so", "sr", "ss", "st", "su", "sv", "sx", "sy", "sz",
    "tc", "td", "tf", "tg", "th", "tj", "tk", "tl", "tm", "tn", "to",
    "tp", "tr", "tt", "tv", "tw", "tz",
    "ua", "ug", "uk", "um", "us", "uy", "uz",
    "va", "vc", "ve", "vg", "vi", "vn", "vu",
    "wf", "ws",
    "ye", "yt", "yu",
    "za", "zm", "zw",
)

DEFAULT_DNS_SERVERS: tuple = (
    "223.5.5.5",
    "119.29.29.29",
    "180.76.76.76",
    "114.114.114.114",
    "8.8.8.8",
    "1.1.1.1",
    "9.9.9.9",
    "208.67.222.222",
)

SPEED_TEST_SERVERS: tuple = (
    ("speed.cloudflare.com", 80, "/__down?bytes=20971520"),
    ("speed.cloudflare.com", 443, "/__down?bytes=20971520"),
    ("httpbin.org", 80, "/stream/20"),
    ("ipv6.speed.cloudflare.com", 80, "/__down?bytes=20971520"),
    ("download.thinkbroadband.com", 80, "/5MB.zip"),
    ("ipv4.download.thinkbroadband.com", 80, "/5MB.zip"),
    ("ipv6.download.thinkbroadband.com", 80, "/5MB.zip"),
)
